### ISSUE TITLE
Posting data broken

### ISSUE THREAD

**Issue by BerniPi** [gjr80/weewx-realtime_gauge-data#14]
Hello!

The upload to a webserver worked for over two months, but suddenly it stopped and in the logs I find the error "rtgdthread: Failed to post data: Unexpected response".

Do you have an idea how to debug this problem?

Dear,
Bernhard

Update: I think, that I have found the problem. My hoster activated a autoredirection to https. Is that a possible cause?

**Comment by gjr80** [comment]
Hi Bernhard,

If _response_text_ is set under _[RealtimeGaugeData]_ rtgd does a fairly simple check on the response received from a web server when posting gauge-data.txt to a web server. The web server should be sending back a response such as 'success'. If that response does not match _response_text_ then the fact is logged. If _response_text_ is not set then no check is performed.

Is gauge-data.txt being correctly posted to your web server? The fact you see this in your log does not mean the file was not posted, it just means the response was not what was expected. I am no web server expert but I guess your providers autodirection to https could have changed the response and thus caused the log entry. If gauge-data.txt is still being correctly posted and updated to your web server then you can ignore the log entry. Obviously if it is not correctly posted and updated we need to look into that. Can you let me know one way or another? In the meantime I will look at changing the code so that we can log the actual response.

Gary

**Comment by BerniPi** [comment]
The file was created successfully on the RaspPi, but the file on the webserver didn't get updated. I tried with another webserver and that worked.

I succeeded in disabling the autoredirection.

Thanks for your help.
Bernhard
