### ISSUE TITLE
gauges not updated!

### ISSUE THREAD

**Issue by sheldon-andrea** [gjr80/weewx-realtime_gauge-data#17]
Hi,
I followed the instructions written in comments on the top of rtgd.py, but it seems that the gauges aren't working, because I don'tn see any update. By rtgd engine I get the following messages:
`rtgd: RealTimeGaugeData scroller text will use a fixed string
rtgd: RealTimeGaugeData will generate gauge-data.txt. min_interval is 2 seconds
rtgd: KeyError: Could not determine sensor contact state`
can you help me?

**Comment by gjr80** [comment]
Hi,

I am happy to help you out but I am going to need a bit more information. I try to keep this issue list for specific bugs with the gauges rather than general support questions. Could I ask you to start a thread in the [WeeWX User Group](https://groups.google.com/forum/?pli=1#!forum/weewx-user) on Google Groups. It would help to see the WeeWX log from startup. If you could stop WeeWX, edit `weewx.conf` and set `debug=1`,  save `weewx.conf` and then restart WeeWX. Let WeeWX run for 5-10 minutes then take a copy of the WeeWX log from when you restarted WeeWX through the 5-10 minutes that you let WeeWX run. Please include the the log extract in your post, include it as is, don't reformat it or change anything. You should find the WeeWX log is in `/var/log/syslog` unless you have changed it.

**Comment by gjr80** [comment]
I will close this issue pending your post to the WeeWX User Group.
