### ISSUE TITLE
Reduce debug = 1 logging

### ISSUE THREAD

**Issue by bakerkj** [gjr80/weewx-realtime_gauge-data#7]
This is a small request to reduce the amount of logging that rtgd creates when debug = 1.  I'd like to suggest changing the logging of the gauge-data.txt generation to only be for debug >= 2.

So changing:
logdbg("rtgdthread", "packet (%s) gauge-data.txt generated in %.5f seconds" % (cached_packet['dateTime'], (self.last_write-t1)))

To:
logdbg2("rtgdthread", "packet (%s) gauge-data.txt generated in %.5f seconds" % (cached_packet['dateTime'], (self.last_write-t1)))

**Comment by gjr80** [comment]
Revised entire debug logging and now support debug=0,1,2 or 3. debug=0 or 1 should result in similar output to standard weeWX with the inclusion of minor (ie non-fatal) rtgd errors (eg failure to post a file) when debug=1. debug=0 or 1 should be tolerable in terms of log volume in the the long term. debug=2 logs queuing/receipt of data and generation of files. debug=3 is as per debug=2 but includes contents of packets/records being processed (ie the data). Due to the volume of log output debug=2 or 3 would normally only be used for short term problem solving.

Implemented at commit https://github.com/gjr80/weewx-realtime_gauge-data/commit/e58bec7f5eea6d308858aee98f3d4381cfafe9c6 (v0.2.13).
